### PR TITLE
Replaces old open source app icons with new.

### PR DESCRIPTION
**Pull request by esreli**

### CODE REVIEW

**Comment by philium** [comment]
It looks like there are a few sizes missing or not hooked up?

image

**Comment by esreli** [comment]
Oddly enough, they weren't provided by the Creative Labs team. Because they are @1x are the necessary?

**Comment by philium** [comment]
> are the necessary?

Probably not. I thought for sure Apple wouldn't show them unless they were necessary, but there are no devices that support iOS 11 (or newer) with a scale factor of 1x. So maybe it is going based off of the logical resolution of supported devices? There are some supported iPads that have the same logical resolution but different scale factors (1x and 2x).

**Comment by philium** [comment]
Since this app is only deployable to iPads, I would suggest unchecking `iPhone` and not including those sizes:

image

**Pull request merged**
